version: 2.1

orbs:
  gor: hubci/goreleaser@1.0

workflows:
  main:
    jobs:
      - test
      - gor/release:
          version: "1.5.0"
          go-version: "1.17.7"
          dry-run: true
          pre-steps:
            - run: sudo apt-get update && sudo apt-get install -y libappindicator3-dev libgtk-3-dev
          post-steps:
            - persist_to_workspace:
                root: "."
                paths:
                  - "dist"
  release:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/
      - gor/release:
          version: "1.5.0"
          go-version: "1.17.7"
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/
          pre-steps:
            - run: sudo apt-get update && sudo apt-get install -y libappindicator3-dev libgtk-3-dev
          post-steps:
            - persist_to_workspace:
                root: "."
                paths:
                  - "dist"
          context: main
      - deb-publish:
          requires:
            - gor/release
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/


jobs:
  test:
    docker:
      - image: cimg/go:1.17.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1
      - run:
          name: "Download Dependancies"
          command: |
            go mod download
            sudo apt-get update && sudo apt-get install -y libappindicator3-dev libgtk-3-dev
      - run:
          name: "Run Tests"
          command: go test
      - run:
          name: "Test Build"
          command: go build
      - save_cache:
          key: go-mod-v1
          paths:
            - "/go/pkg/mod"
  deb-publish:
    docker:
      - image: cimg/base:current
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys
      - run: |
          echo 'pkg.atl.revidian.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBE16slz1okRPeUhxIpzBCn9rHqjk51ylxEYlYXvblswcxOQ0rPyAX6N8Bd2pnsh99xce/jaX2KJHPLPCc+zAXTg= root@li361-16' >> ~/.ssh/known_hosts
      - run: |
          ssh pkg@pkg.atl.revidian.net "mkdir ~/incoming/tailscale-appindicator-${CIRCLE_TAG}"
          scp ./dist/*.deb pkg@pkg.atl.revidian.net:incoming/tailscale-appindicator-${CIRCLE_TAG}/

          # Ubuntu 20.04 Focal
          ssh pkg@pkg.atl.revidian.net "aptly repo add ftech-ubuntu-focal ~/incoming/tailscale-appindicator-${CIRCLE_TAG}/"
          ssh pkg@pkg.atl.revidian.net "aptly snapshot create ftech-ubuntu-focal--tailscale-appindicator-${CIRCLE_TAG} from repo ftech-ubuntu-focal"
          ssh pkg@pkg.atl.revidian.net "aptly publish switch focal filesystem:ftech:/ubuntu ftech-ubuntu-focal--tailscale-appindicator-${CIRCLE_TAG}"


          # Ubuntu 21.10 Impish
          ssh pkg@pkg.atl.revidian.net "aptly repo add ftech-ubuntu-impish ~/incoming/tailscale-appindicator-${CIRCLE_TAG}/"
          ssh pkg@pkg.atl.revidian.net "aptly snapshot create ftech-ubuntu-impish--tailscale-appindicator-${CIRCLE_TAG} from repo ftech-ubuntu-impish"
          ssh pkg@pkg.atl.revidian.net "aptly publish switch impish filesystem:ftech:/ubuntu ftech-ubuntu-impish--tailscale-appindicator-${CIRCLE_TAG}"

          # Ubuntu 22.04 Jammy
          ssh pkg@pkg.atl.revidian.net "aptly repo add ftech-ubuntu-jammy ~/incoming/tailscale-appindicator-${CIRCLE_TAG}/"
          ssh pkg@pkg.atl.revidian.net "aptly snapshot create ftech-ubuntu-jammy--tailscale-appindicator-${CIRCLE_TAG} from repo ftech-ubuntu-jammy"
          ssh pkg@pkg.atl.revidian.net "aptly publish switch jammy filesystem:ftech:/ubuntu ftech-ubuntu-jammy--tailscale-appindicator-${CIRCLE_TAG}"

          ssh pkg@pkg.atl.revidian.net "rm -r ~/incoming/tailscale-appindicator-${CIRCLE_TAG}"
